import './globals.css';
import { getContactInfo, getRoutes } from '@/client';

import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { Assistant } from 'next/font/google';

const assistFont = Assistant({
	subsets: ['latin'],
	display: 'swap',
});

export const metadata = {
	title: 'Doron',
	description: 'Generated by barel31 with create next app',
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const routes = await getRoutes;
	const contactInfo = await getContactInfo;

	return (
		<html lang="he" className={assistFont.className} dir="rtl">
			<body>
				<Header routes={routes} contact={contactInfo} />

				<main>
					{children}
				</main>

				<Footer routes={routes} contact={contactInfo} />
			</body>
		</html>
	);
}
